site_name: The Knowledge Atlas
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.grid
  version:
    provider: mike

markdown_extensions:
  - attr_list      # Required to recognize the "grid cards" class
  - md_in_html     # Required to process Markdown inside the <div>
  
nav:
  - Home: index.md
  - Biology:
      - biology/index.md
      - Chapter 1: biology/chapter-1.md
  - Physics:
      - physics/index.md
      - Chapter 1: physics/chapter-1.md
  - Meet the Team: team.md